feat: More asm unittests
matter-labs/era-zkevm_test_harness pull request #142
Opened 2024-05-20 15:24 UTC by mm-zk

# What ❔
* Adding more ASM based unittests for circuits
* covering storage reads, writes and decommit instructions.

2024-05-21 09:21 UTC, 0xVolosnikov requested changes

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/decommit_ok/entry.asm
> +        ; we expect the near_call to panic
Seems like we do not expect the near_call to panic at all

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/decommit_ok/entry.asm
> +        ; We should never get here - as the near_call should panic due to out of gas.
Invalid coment

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/decommit_ok_with_panic/entry.asm
> +        ret.ok r0
Imo it is better to use `ret.panic` here. So this test will fail if "inner" do not panic.

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/decommit_ok_with_panic/entry.asm
> +        ret.panic r0
Should be `ret.ok r0` otherwise we can have false-negatives.

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/log_custom/entry.asm
> +        ; We should never get here - as the near_call should panic due to out of gas.
It is not clear why we are doing near_call at all. And also there are invalid comments

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/storage_reads/entry.asm
> +	    .cell 452312938437537823148903869859771978505772238111866864847149311043017845250
Not used

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/storage_reads/entry.asm
> +        add 15, r0, r1
Deadcode 

https://github.com/matter-labs/era-zkevm_test_harness/pull/142/files#diff-92897e91c359336ad84be6ea4fc47fddb5db39b5dbf07ea4763473594062e5e1R22-R57

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/storage_reads/entry.asm
> +        ; assert r5 == 18
; assert r5 == 0

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/storage_reads/entry.asm
> +        ; write 15 to position 18
```suggestion
        ; write 18 to position 15
```

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/storage_reads/entry.asm
> +        add 15, r0, r1
So `twrite` and `tread` aren't tested

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/storage_writes/entry.asm
> +        ; check pubdata counter (should be equal to 130 - from the first 2 writes)
`-` is a little bit confusing
```suggestion
        ; check pubdata counter (should be equal to 130: from the first 2 writes)
```

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/storage_writes/entry.asm
> +
```suggestion

; we'll be writing 24 at slot 25
```

2024-05-21 09:21 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/storage_writes/entry.asm
> +        ret.panic r0
We should panic globally in this case 
```suggestion
        ret.ok r0
```

2024-05-22 07:42 UTC, mm-zk commented on src/tests/simple_tests/testdata/log_custom/entry.asm
> +        ; We should never get here - as the near_call should panic due to out of gas.
yes, this test was used to creating more tests. Removed.

2024-05-22 08:04 UTC, mm-zk commented on src/tests/simple_tests/testdata/storage_reads/entry.asm
> +        add 15, r0, r1
fixed.

2024-05-22 08:16 UTC, 0xVolosnikov commented
Wouldn't it be easier if we hadn't been forcing the name of asm file to be "entry.asm"? For instance, use one directory for "storage" tests with "storage_reads.asm", "storage_writes.asm" etc? And subdirectory "additional_contracts" or smth to share additional contracts between different tests?

2024-05-22 08:18 UTC, mm-zk commented
the original goal, was for each test to have its separate  'ecosystem' - as I was focusing on far_calls that required multiple contracts to be present.

But yes, if we have many tests that are single-file, then we can do what you suggest - and change the code to just load that test name.
I'd do it in separate PR.

2024-05-22 08:29 UTC, 0xVolosnikov approved these changes

2024-05-22 08:29 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/decommit_ok/entry.asm
> +        log.event r9, r10, r0
Cleanup debug?

2024-05-22 08:29 UTC, 0xVolosnikov commented on src/tests/simple_tests/testdata/decommit_ok/entry.asm
> +        log.event r10, r11, r0
Cleanup debug?

2024-05-24 08:43 UTC, merged