Move lazy static values to heap
matter-labs/era-zkevm_test_harness pull request #72
Opened 2024-01-24 02:15 UTC by jules

# What ❔

Moves lazy static consts to the heap.

## Why ❔

There were reports of stack overflows on certain hardware.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `zk fmt` and `zk lint`.

2024-01-29 18:01 UTC, shamatar requested changes

2024-01-29 18:01 UTC, shamatar commented on src/kzg/mod.rs
> +            .map(|r| if *r != Fr::one() { r.inverse().unwrap() } else { *r })
There is no point in special casing here

2024-01-29 18:01 UTC, shamatar commented on src/kzg/mod.rs
> +    static ref ROOTS_OF_UNITY: Vec<Fr> = {
Either `Box<[Fr; 4096]>` or `Box<[Fr]>`, you never need static immutable vector

2024-01-29 18:01 UTC, shamatar commented on src/kzg/mod.rs
> +            let mut el = el.clone();
it's copiable, so `iter().copied()` or just `let el = *el` is sufficient

2024-02-01 20:53 UTC, koloz193 commented
closing as changes were covered in https://github.com/matter-labs/era-zkevm_test_harness/pull/77

2024-02-01 20:53 UTC, closed without merging