Fix challenge computation
matter-labs/era-zkevm_test_harness pull request #75
Opened 2024-01-28 18:25 UTC by jules

# What ❔

Fixes challenge computation to match the KZG spec.

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.
- [x] Code has been formatted via `zk fmt` and `zk lint`.

2024-01-29 17:58 UTC, shamatar commented on src/kzg/mod.rs
> +                .collect::<Vec<u8>>()
you need a length assert here, and did they really decide to make a commitment based on the full blob bytes? This is strange move

2024-01-29 17:59 UTC, shamatar requested changes

2024-01-29 17:59 UTC, shamatar commented on src/kzg/mod.rs
> +    for i in 0..ret.len() {
we use nightly, so just do `array_chunks` instead

2024-01-29 18:17 UTC, jules commented on src/kzg/mod.rs
> +                .collect::<Vec<u8>>()
Yeah, as shown in the [consensus spec](https://github.com/ethereum/consensus-specs/blob/86fb82b221474cc89387fa6436806507b3849d88/specs/deneb/polynomial-commitments.md#compute_challenge) it requires the entire blob

2024-02-05 15:01 UTC, shamatar commented on src/kzg/mod.rs
> +    let degree_separator: [u8; 16] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x10, 0];
Are you sure about endianess here?

2024-02-05 15:01 UTC, shamatar commented on src/kzg/mod.rs
> +                .collect::<Vec<u8>>()
Ok, but there is a much more efficient way to put all the bytes instead of tons on internal allocations

2024-02-05 15:01 UTC, shamatar commented on src/kzg/mod.rs
> +                .collect::<Vec<u8>>()
And ideally you should just put everything into main buffer directly

2024-02-05 15:01 UTC, shamatar commented on src/kzg/mod.rs
> +    data.extend(commitment.into_compressed().as_ref());
Did you check that pairing's format of compression is the same as in 4844? It was quite custom

2024-02-05 15:01 UTC, shamatar commented on src/kzg/mod.rs
>  fn u8_repr_to_u64_repr(bytes: [u8; 32]) -> [u64; 4] {
name endianess in function name

2024-02-05 15:01 UTC, shamatar commented on src/kzg/mod.rs
> +    for (i, chunk) in bytes.array_chunks::<8>().enumerate() {
Please less index use, more "zip" and "iter_mut()" for destination

2024-02-05 15:10 UTC, jules commented on src/kzg/mod.rs
> +    let degree_separator: [u8; 16] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x10, 0];
yes, it was compared to onchain data, the degree separator is big endian

2024-02-05 15:12 UTC, jules commented on src/kzg/mod.rs
> +    data.extend(commitment.into_compressed().as_ref());
yes, also checked against onchain data - the default function here passed and no need to swap endianness

2024-02-05 15:37 UTC, koloz193 approved these changes
tested against mainnet blob/commitment and tests are passing

2024-02-05 15:38 UTC, merged